apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment1
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: rahul7rajdn/helloworld:2
        ports:
        - containerPort: 3000
