apiVersion: v1
kind: Service
metadata:
  name: my-service1
spec:
  selector:
    app: hello-world
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000

